import type { Category, Product } from "@/types/catalog";

export const categories: Category[] = [
  {
    id: "cat-electronics",
    slug: "electronics",
    name: "Electronics",
    description: "Phones, laptops, audio and smart home",
    productCount: 128,
  },
  {
    id: "cat-fashion",
    slug: "fashion",
    name: "Fashion",
    description: "Apparel, footwear and accessories",
    productCount: 246,
  },
  {
    id: "cat-home",
    slug: "home-kitchen",
    name: "Home & Kitchen",
    description: "Appliances, cookware and decor",
    productCount: 97,
  },
  {
    id: "cat-beauty",
    slug: "beauty",
    name: "Beauty",
    description: "Skincare, haircare and grooming",
    productCount: 84,
  },
  {
    id: "cat-sports",
    slug: "sports",
    name: "Sports",
    description: "Fitness gear and outdoor equipment",
    productCount: 61,
  },
  {
    id: "cat-books",
    slug: "books",
    name: "Books",
    description: "Bestsellers, exam prep and comics",
    productCount: 173,
  },
  {
    id: "cat-grocery",
    slug: "grocery",
    name: "Grocery",
    description: "Pantry staples and daily essentials",
    productCount: 52,
  },
  {
    id: "cat-toys",
    slug: "toys",
    name: "Toys",
    description: "Games, STEM kits and kids picks",
    productCount: 39,
  },
];

export const featuredProducts: Product[] = [
  {
    id: "prod-1",
    slug: "noise-cancelling-headphones",
    title: "AeroPulse NC Headphones",
    description: "Over-ear wireless headphones with 40-hour battery life.",
    price: 7999,
    currency: "INR",
    categorySlug: "electronics",
    categoryName: "Electronics",
    featured: true,
    rating: 4.6,
    accent: "#0f766e",
  },
  {
    id: "prod-2",
    slug: "stainless-steel-cookware-set",
    title: "Forge 5-Piece Cookware Set",
    description: "Tri-ply stainless steel pots and pans for everyday cooking.",
    price: 5499,
    currency: "INR",
    categorySlug: "home-kitchen",
    categoryName: "Home & Kitchen",
    featured: true,
    rating: 4.4,
    accent: "#b45309",
  },
  {
    id: "prod-3",
    slug: "everyday-running-shoes",
    title: "StrideLite Running Shoes",
    description: "Cushioned road runners built for daily training.",
    price: 4299,
    currency: "INR",
    categorySlug: "sports",
    categoryName: "Sports",
    featured: true,
    rating: 4.5,
    accent: "#1d4ed8",
  },
  {
    id: "prod-4",
    slug: "vitamin-c-serum",
    title: "Lumen Vitamin C Serum",
    description: "Brightening serum with hyaluronic acid and niacinamide.",
    price: 899,
    currency: "INR",
    categorySlug: "beauty",
    categoryName: "Beauty",
    featured: true,
    rating: 4.3,
    accent: "#be185d",
  },
  {
    id: "prod-5",
    slug: "linen-overshirt",
    title: "Coastal Linen Overshirt",
    description: "Breathable regular-fit overshirt for warm weather.",
    price: 2199,
    currency: "INR",
    categorySlug: "fashion",
    categoryName: "Fashion",
    featured: true,
    rating: 4.2,
    accent: "#0f172a",
  },
  {
    id: "prod-6",
    slug: "product-strategy-handbook",
    title: "The Product Strategy Handbook",
    description: "A practical guide to discovery, positioning and growth.",
    price: 649,
    currency: "INR",
    categorySlug: "books",
    categoryName: "Books",
    featured: true,
    rating: 4.7,
    accent: "#7c3aed",
  },
];

export function formatPrice(amount: number, currency: Product["currency"] = "INR"): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency,
    maximumFractionDigits: 0,
  }).format(amount);
}
